# Generated by Django 5.2.5 on 2025-09-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('World', 'World'), ('Science', 'Science'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Environment', 'Environment'), ('Opinion', 'Opinion'), ('Culture', 'Culture'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('History', 'History'), ('Music', 'Music'), ('Art', 'Art'), ('Religion', 'Religion'), ('Other', 'Other')], default='Politics', max_length=50),
        ),
    ]
