# Generated by Django 5.2.5 on 2026-04-21 16:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_seed_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
